name: Release PDF Resume

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1

      - name: Render PDF
        run: quarto render resume.qmd --to pdf

      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}